import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col relative bg-[#0a0a0a]" style={{ fontFamily: "'DM Sans', sans-serif" }}>
      {/* Grain */}
      <div className="grain" aria-hidden="true" />

      {/* Ambient glow */}
      <div
        aria-hidden="true"
        className="fixed inset-0 pointer-events-none z-0"
        style={{ background: "radial-gradient(ellipse 70% 40% at 50% -5%, rgba(255,94,58,0.06) 0%, transparent 65%)" }}
      />

      <Navbar />

      <main
        style={{
          padding: "80px clamp(24px, 6vw, 80px) 120px",
          flex: 1,
          position: "relative",
          zIndex: 10,
          width: "100%",
          maxWidth: "800px",
          margin: "0 auto",
        }}
      >
        <header className="mb-16 fade-up-1">
          <h1 className="text-5xl font-black text-white mb-6 tracking-tight">Terms of Service</h1>
          <p className="text-white/40 text-lg">Last updated: March 19, 2026</p>
        </header>

        <section className="fade-up-2 prose prose-invert max-w-none" style={{ color: "rgba(255,255,255,0.6)", lineHeight: 1.8 }}>
          <div className="space-y-12">
            <div>
              <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using this color palette generator, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-4">2. Use of the Service</h2>
              <p>
                Our service is provided for personal and commercial use. You are free to use any color palettes generated by our tool in your own projects without attribution, though we always appreciate a shout-out!
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-4">3. Prohibited Activities</h2>
              <p>
                You may not use our service to generate content that is unlawful, harmful, or violates the rights of others. You may not attempt to disrupt the service or its underlying infrastructure.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-4">4. Intellectual Property</h2>
              <p>
                The designs, code, and brand elements of this application remain the property of the developers. Individual color combinations (palettes) are considered non-copyrightable data, and you are free to use them.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-4">5. Disclaimer</h2>
              <p>
                The service is provided "as is" without warranties of any kind. We are not responsible for any issues that may arise from using the colors or the software.
              </p>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
